apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hellok8s
spec:
  replicas: 15
  template:
    metadata:
      labels:
        name: hellok8s
    spec:
      containers:
      - name: hellok8s
        image: gcr.io/angel-nunez/hellok8s:2.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080