apiVersion: v1
kind: LimitRange
metadata:
  name: development-limitrange
spec:
  limits:
    - type: Pod
      max:
        cpu: 2
        memory: 1Gi
      min:
        cpu: 100m
        memory: 100Mi
    - type: Container
      default:
        cpu: 300m
        memory: 200Mi
      defaultRequest:
        cpu: 200m
        memory: 100Mi
      max:
        cpu: "2"
        memory: 1Gi
      min:
        cpu: 100m
        memory: 50Mi