apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    name: hellok8s
spec:
  containers:
  - name: hellok8s
    image: gcr.io/angel-nunez/hellok8s:1.0
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 8080