apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
spec:
  #type: NodePort
  #   NodePort allows to expose the service in a internal port that are shared across the entire cluster.
  type: LoadBalancer
  #   LoadBalancer  automatically create an "external" load-balanced IP for the frontend service.
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: guestbook
    tier: frontend
